name: PurpleHey
description: "'scuse me While I think out loud..."

url: "http://localhost:4000"

paginate: 10

markdown: rdiscount
permalink: :title
highlighter: pygments

excerpt_separator: <!--more-->  # you can specify your own separator, of course.

image: /assets/frontPorch.jpg

gems:
  - jekyll-auto-image